configuration: Release

init:
  - git config --global core.autocrlf true
  
install:
  - GitVersion /output buildserver /UpdateAssemblyInfo true
  - choco install resharper-clt -y
  - choco install opencover.portable -y
  - choco install nvika -y
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov

cache:
- src/packages -> **\packages.config
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml

before_build:
  - nuget restore src

build:
  project: src/ScriptCs.ComponentModel.Composition.sln
  verbosity: minimal

after_build:
  - inspectcode /o="inspectcodereport.xml" "src/ScriptCs.ComponentModel.Composition.sln"
  - NVika parsereport "inspectcodereport.xml" --debug --includesource
# build nuget package
  - mkdir NugetAssets
  - nuget pack src\ScriptCs.ComponentModel.Composition\ScriptCs.ComponentModel.Composition.csproj -Version %GitVersion_NuGetVersion% -OutputDirectory %appveyor_build_folder%\NugetAssets\ -symbols

test_script:
  - "%xunit20%\xunit.console.x86.exe" %APPVEYOR_BUILD_FOLDER%\src\ScriptCs.ComponentModel.Composition.Test\bin\Release\ScriptCs.ComponentModel.Composition.Test.dll -noshadow -appveyor
  # - OpenCover.Console.exe -register:user -filter:"+[ScriptCs.ComponentModel.Composition]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"`"%APPVEYOR_BUILD_FOLDER%\src\ScriptCs.ComponentModel.Composition.Test\bin\Release\ScriptCs.ComponentModel.Composition.Test.dll`" -noshadow -appveyor" -output:coverage.xml -returntargetcode

after_test:
  - codecov -f coverage.xml

artifacts:
  - path: inspectcodereport.xml
  - path: coverage.xml

  - path: src\ScriptCs.ComponentModel.Composition\bin\Release\ScriptCs.ComponentModel.Composition.dll.CodeAnalysisLog.xml
    name: ScriptCs.ComponentModel.Composition.dll.CodeAnalysisLog.xml

  - path: NugetAssets\ScriptCs.ComponentModel.Composition.*.symbols.nupkg
    name: ScriptCs.ComponentModel.Composition.symbols.nupkg

  - path: NugetAssets\ScriptCs.ComponentModel.Composition.*.nupkg
    name: ScriptCs.ComponentModel.Composition.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: NmM24h0TPsfINvy/1Qr4iJkmRjVztuY5umCJ6mzpxSjvuKl48AXjGEcgow+iJwL8
    on:
      appveyor_repo_tag: true
