configuration: Release

init:
  - git config --global core.autocrlf true
  
install:
  - GitVersion /output buildserver /UpdateAssemblyInfo true
  - choco install opencover.portable -y
  - choco install coveralls.io -source https://nuget.org/api/v2/ -y
  - choco install nvika -y

#cache:
#  - packages -> **\packages.config
#  - C:\ProgramData\chocolatey\bin\inspectcode.exe -> appveyor.yml
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  COVERALLS_REPO_TOKEN:
    secure: mzA3KujNlhtanIr2YQn90ZQdEQm1dGB9UJrgrZexSySIYHwUszIT2XYv37tuqDsF

before_build:
  - nuget restore src

build:
  project: src/ScriptCs.ComponentModel.Composition.sln
  verbosity: minimal

after_build:
  - NVika parsereport "src\ScriptCs.ComponentModel.Composition\bin\Release\static-analysis.sarif.json" --debug --includesource
# build nuget package
  - mkdir NugetAssets
  - nuget pack src\ScriptCs.ComponentModel.Composition\ScriptCs.ComponentModel.Composition.csproj -Version %GitVersion_NuGetVersion% -OutputDirectory %appveyor_build_folder%\NugetAssets\ -symbols

test_script:
  - ps: .\RunTests.ps1

artifacts:
  - path: src\ScriptCs.ComponentModel.Composition\bin\Release\static-analysis.sarif.json
    name: static-analysis.sarif.json

  - path: src\ScriptCs.ComponentModel.Composition\bin\Release\ScriptCs.ComponentModel.Composition.dll.CodeAnalysisLog.xml
    name: ScriptCs.ComponentModel.Composition.dll.CodeAnalysisLog.xml

  - path: NugetAssets\ScriptCs.ComponentModel.Composition.*.symbols.nupkg
    name: ScriptCs.ComponentModel.Composition.symbols.nupkg

  - path: NugetAssets\ScriptCs.ComponentModel.Composition.*.nupkg
    name: ScriptCs.ComponentModel.Composition.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: NmM24h0TPsfINvy/1Qr4iJkmRjVztuY5umCJ6mzpxSjvuKl48AXjGEcgow+iJwL8
    on:
      appveyor_repo_tag: true
